# This file was generated by GoReleaser. DO NOT EDIT.
cask "acme-for-appliances" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "7540814f91141d15670d21010d19c886447e67ca6bb4665f53ae302182d0b520"
      url "https://github.com/BeryJu/acme-for-appliances/releases/download/v#{version}/acme-for-appliances_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1f848ce048f9436416ea6e4fa200dc3ea37c4858c6d769f28b5b0ad11398c248"
      url "https://github.com/BeryJu/acme-for-appliances/releases/download/v#{version}/acme-for-appliances_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "79118f1784a80d9320d9ee50680b5a9ed2b04d3b5cc11a252f38b4b8dad814cf"
      url "https://github.com/BeryJu/acme-for-appliances/releases/download/v#{version}/acme-for-appliances_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "557eae7d2a166f7862427bf90b0c002140a63219d017e8e7170ee902c80e444d"
      url "https://github.com/BeryJu/acme-for-appliances/releases/download/v#{version}/acme-for-appliances_#{version}_linux_arm64.tar.gz"
    end
  end

  name "acme-for-appliances"
  desc "ACME Support for appliances that don't natively support it"
  homepage "https://github.com/BeryJu/acme-for-appliances"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "acme-for-appliances"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/acme-for-appliances"]
    end
  end

  # No zap stanza required

end
