# This file was generated by GoReleaser. DO NOT EDIT.
cask "acme-for-appliances" do
  desc "ACME Support for appliances that don't natively support it"
  homepage "https://github.com/beryju/acme-for-appliances"
  version "1.2.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "acme-for-appliances"

  on_macos do
    on_intel do
      url "https://github.com/BeryJu/acme-for-appliances/releases/download/v1.2.3/acme-for-appliances_darwin_amd64"
      sha256 "db1cf44c8e893908944727114594bd392dab429095d72553e15fcfb3d1d6949c"
    end
    on_arm do
      url "https://github.com/BeryJu/acme-for-appliances/releases/download/v1.2.3/acme-for-appliances_darwin_arm64"
      sha256 "b7808cbdfe9e65e2b9061af36d083c1d0d11f1e1fd314cf57967447f860e9fe0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/BeryJu/acme-for-appliances/releases/download/v1.2.3/acme-for-appliances_linux_amd64"
      sha256 "f65fa2edd9550b9383ad883edcba23add71a986134d51f932a8e56ca00b34aae"
    end
    on_arm do
      url "https://github.com/BeryJu/acme-for-appliances/releases/download/v1.2.3/acme-for-appliances_linux_arm64"
      sha256 "a0d2ea5a29d1004acf942a89f5205d7504f13e8aea72f9cc24db4cde832baa1c"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/acme-for-appliances"]
    end
  end

  # No zap stanza required
end
