# This file was generated by GoReleaser. DO NOT EDIT.
cask "acme-for-appliances" do
  desc "ACME Support for appliances that don't natively support it"
  homepage "https://github.com/BeryJu/acme-for-appliances"
  version "1.2.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "acme-for-appliances"

  on_macos do
    on_intel do
      url "https://github.com/BeryJu/acme-for-appliances/releases/download/v1.2.6/acme-for-appliances_1.2.6_darwin_amd64.tar.gz"
      sha256 "bd322fc1053a68047dfd4365dd284a6b396801ead7e2ee20304205ea9a1e5bc3"
    end
    on_arm do
      url "https://github.com/BeryJu/acme-for-appliances/releases/download/v1.2.6/acme-for-appliances_1.2.6_darwin_arm64.tar.gz"
      sha256 "448557cbd3edf9694a3fa44d3a5f3c826494a7d2f296cd27c78180aa6fb2fa9c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/BeryJu/acme-for-appliances/releases/download/v1.2.6/acme-for-appliances_1.2.6_linux_amd64.tar.gz"
      sha256 "27a369dfec742b3d3b6993a26d1278110f2938711330d8e9589c66c35d8ca422"
    end
    on_arm do
      url "https://github.com/BeryJu/acme-for-appliances/releases/download/v1.2.6/acme-for-appliances_1.2.6_linux_arm64.tar.gz"
      sha256 "cc6c14df43af4954cab94fb77eaf9b4dda917ade48e95965bf8eb634701080ea"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/acme-for-appliances"]
    end
  end

  # No zap stanza required
end
