# This file was generated by GoReleaser. DO NOT EDIT.
cask "crtls" do
  desc "Tool for creating a CA and Certificates, mainly aimed at testing setups"
  homepage "https://github.com/BeryJu/crtls"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crtls"
  bash_completion "completions/crtls.bash"
  zsh_completion "completions/crtls.zsh"
  fish_completion "completions/crtls.fish"

  on_macos do
    on_intel do
      url "https://github.com/BeryJu/crtls/releases/download/v0.1.2/crtls_0.1.2_darwin_amd64.tar.gz"
      sha256 "6c56b22eee89c5ec8c710d5e57b1e4195403b5c0ebf3aa87829da3a45a49a67e"
    end
    on_arm do
      url "https://github.com/BeryJu/crtls/releases/download/v0.1.2/crtls_0.1.2_darwin_arm64.tar.gz"
      sha256 "5d4d1c68bd439e2c1f64634c5f969246ed406e6b9320bef7c54b09cc702426f6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/BeryJu/crtls/releases/download/v0.1.2/crtls_0.1.2_linux_amd64.tar.gz"
      sha256 "d81aa24eb0dc7582c9eecfb38376cb6d56b69174a2c6d3d7ebbf36dd5bb407a7"
    end
    on_arm do
      url "https://github.com/BeryJu/crtls/releases/download/v0.1.2/crtls_0.1.2_linux_arm64.tar.gz"
      sha256 "1d74e2a0c6ea3537da310cb6e33dd82090e37aa94b67a79de9156b675170ddc6"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/crtls"]
    end
  end

  # No zap stanza required
end
