# This file was generated by GoReleaser. DO NOT EDIT.
cask "crtls" do
  desc "Tool for creating a CA and Certificates, mainly aimed at testing setups"
  homepage "https://github.com/BeryJu/crtls"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crtls"
  bash_completion "completions/crtls.bash"
  zsh_completion "completions/crtls.zsh"
  fish_completion "completions/crtls.fish"

  on_macos do
    on_intel do
      url "https://github.com/BeryJu/crtls/releases/download/v0.1.3/crtls_0.1.3_darwin_amd64.tar.gz"
      sha256 "f61fd1c579db186077030342b509a33e0528c73bce6035aff642d429d1d0f9a2"
    end
    on_arm do
      url "https://github.com/BeryJu/crtls/releases/download/v0.1.3/crtls_0.1.3_darwin_arm64.tar.gz"
      sha256 "9a36622acc9f5d96665d51fbaf2fc08db2e99c1385231cdfd13e8c7cd53c30db"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/BeryJu/crtls/releases/download/v0.1.3/crtls_0.1.3_linux_amd64.tar.gz"
      sha256 "129e3226a2572ce86b4ed02eb05648c628fb684caf82b73bc1999832e05c8eca"
    end
    on_arm do
      url "https://github.com/BeryJu/crtls/releases/download/v0.1.3/crtls_0.1.3_linux_arm64.tar.gz"
      sha256 "f01b6ca197cd8883b22a48ec62210e753004b576ce993550d6f17e4a698031de"
    end
  end

  on_macos do
    postflight do
      if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/crtls"]
      end
    end
  end

  # No zap stanza required
end
