# This file was generated by GoReleaser. DO NOT EDIT.
cask "crtls" do
  on_macos do
    postflight do
      if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/crtls"]
      end
    end
  end

  name "crtls"
  desc "Tool for creating a CA and Certificates, mainly aimed at testing setups"
  homepage "https://github.com/BeryJu/crtls"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crtls"
  bash_completion "completions/crtls.bash"
  zsh_completion "completions/crtls.zsh"
  fish_completion "completions/crtls.fish"

  on_macos do
    on_intel do
      url "https://github.com/BeryJu/crtls/releases/download/v#{version}/crtls_#{version}_darwin_amd64.tar.gz"
      sha256 "c4866943b8f4d6b1b94804a02c889f8cb092c8e53f725ce5757cba1085ce22d8"
    end
    on_arm do
      url "https://github.com/BeryJu/crtls/releases/download/v#{version}/crtls_#{version}_darwin_arm64.tar.gz"
      sha256 "33523407ef635dabac6c6acf7d636f262db5cde8d2257af5bc3e21c40d194b3b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/BeryJu/crtls/releases/download/v#{version}/crtls_#{version}_linux_amd64.tar.gz"
      sha256 "4a0ddadae1cffd87d50b73951e996a672c7aa42ec4e5e776bb64aaf542ffec70"
    end
    on_arm do
      url "https://github.com/BeryJu/crtls/releases/download/v#{version}/crtls_#{version}_linux_arm64.tar.gz"
      sha256 "761f153df75e707f235c2474a49831ef1b1e9269f0826ee171dfa9283f28f78c"
    end
  end

  # No zap stanza required
end
