# This file was generated by GoReleaser. DO NOT EDIT.
cask "korb" do
  desc "Move Kubernetes PVCs between Storage Classes and Namespaces"
  homepage "https://github.com/beryju/korb"
  version "2.3.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "korb"

  on_macos do
    on_intel do
      url "https://github.com/BeryJu/korb/releases/download/v2.3.4/korb_2.3.4_darwin_amd64.tar.gz"
      sha256 "7835e83c4d8aed7357c2fd48f1a68634ca08d01317800b6997372b3728598308"
    end
    on_arm do
      url "https://github.com/BeryJu/korb/releases/download/v2.3.4/korb_2.3.4_darwin_arm64.tar.gz"
      sha256 "a8295da1620e862a5f6611b942ab95c99b842bf52ef6bde9c953056fff5667ca"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/BeryJu/korb/releases/download/v2.3.4/korb_2.3.4_linux_amd64.tar.gz"
      sha256 "892213c9a11d2cb87d5db374344b27cba48801380c9c8582863880dce493e5ce"
    end
    on_arm do
      url "https://github.com/BeryJu/korb/releases/download/v2.3.4/korb_2.3.4_linux_arm64.tar.gz"
      sha256 "fa4e127eac7f2346d0e0c819c3e89680f9e8d10a0d1f617d8fd2be8b85d4b861"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/korb"]
    end
  end

  # No zap stanza required
end
