# This file was generated by GoReleaser. DO NOT EDIT.
cask "korb" do
  desc "Move Kubernetes PVCs between Storage Classes and Namespaces"
  homepage "https://github.com/beryju/korb"
  version "2.3.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "korb"

  on_macos do
    on_intel do
      url "https://github.com/BeryJu/korb/releases/download/v2.3.3/korb_darwin_amd64"
      sha256 "4a57067bb7403b57e89338d2626421a7709fb06942f7f8759262781cf7663203"
    end
    on_arm do
      url "https://github.com/BeryJu/korb/releases/download/v2.3.3/korb_darwin_arm64"
      sha256 "90649fa3b487e443a3a75a977799d2781cd06537957110af2c8a15b337ad18ca"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/BeryJu/korb/releases/download/v2.3.3/korb_linux_amd64"
      sha256 "11c7ffd44572ea48e6fe41a5c61cd7e28690bc999a61c64b95f1755e44bb82f5"
    end
    on_arm do
      url "https://github.com/BeryJu/korb/releases/download/v2.3.3/korb_linux_arm64"
      sha256 "7c50e20e89664c17ef4f601960081643b11cfb0e799be14c23056352370b1689"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/korb"]
    end
  end

  # No zap stanza required
end
