# This file was generated by GoReleaser. DO NOT EDIT.
cask "oidc-test-client" do
  desc "Small, OIDC Client, to debug and test OIDC providers"
  homepage "https://github.com/beryju/oidc-test-client"
  version "2.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oidc-test-client"

  on_macos do
    on_intel do
      url "https://github.com/BeryJu/oidc-test-client/releases/download/v2.6/oidc-test-client_2.6_darwin_amd64.tar.gz"
      sha256 "b5313a9040e7b1aec22733b570612347c80a2e72d882eb11f014a1af6bb80be0"
    end
    on_arm do
      url "https://github.com/BeryJu/oidc-test-client/releases/download/v2.6/oidc-test-client_2.6_darwin_arm64.tar.gz"
      sha256 "ee9afc94fb6f1a0d6fcafca03cc9c88bf54c4ac33b3ba5acc749d4d0f6d2e486"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/BeryJu/oidc-test-client/releases/download/v2.6/oidc-test-client_2.6_linux_amd64.tar.gz"
      sha256 "36212fffe1d3e1105b774ca199373dc984d30be08d9dd00a6564d3af295a52da"
    end
    on_arm do
      url "https://github.com/BeryJu/oidc-test-client/releases/download/v2.6/oidc-test-client_2.6_linux_arm64.tar.gz"
      sha256 "c5d8fb13b92ad8b5f2290d1446a71f02a3fff1c34978ec9c901b21c49ad1334e"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/oidc-test-client"]
    end
  end

  # No zap stanza required
end
