# This file was generated by GoReleaser. DO NOT EDIT.
cask "oidc-test-client" do
  desc "Small, OIDC Client, to debug and test OIDC providers"
  homepage "https://github.com/beryju/oidc-test-client"
  version "2.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oidc-test-client"

  on_macos do
    on_intel do
      url "https://github.com/BeryJu/oidc-test-client/releases/download/v2.5/oidc-test-client_darwin_amd64"
      sha256 "ac4786a817d757e216ca5fa5f3b54efcad562eeac4f967a6b73d93442be79d95"
    end
    on_arm do
      url "https://github.com/BeryJu/oidc-test-client/releases/download/v2.5/oidc-test-client_darwin_arm64"
      sha256 "7e6915d80b18d4463549fcc23f1e61fa72fe1ce34ab60b3424c623241054f9c8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/BeryJu/oidc-test-client/releases/download/v2.5/oidc-test-client_linux_amd64"
      sha256 "af66f6662cad1e26a81d6622aa844bb5ff999317279afa4e0573a76441c2301c"
    end
    on_arm do
      url "https://github.com/BeryJu/oidc-test-client/releases/download/v2.5/oidc-test-client_linux_arm64"
      sha256 "b4ebcc7f0ab6957588ac3714e7bd417c474fa3719b58be02dfec1fcb53706b7c"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/oidc-test-client"]
    end
  end

  # No zap stanza required
end
