# This file was generated by GoReleaser. DO NOT EDIT.
cask "oidc-test-client" do
  version "2.7.1"

  on_macos do
    on_arm do
      sha256 "3e54c34ffac7787ee05c1a85efc61d298213d883348f5d7a7f3cb675e9fed4e5"
      url "https://github.com/BeryJu/oidc-test-client/releases/download/v#{version}/oidc-test-client_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "aa4f533144fdedeb9200720402cfc96570509988899ffa50dfdf71f202df5d43"
      url "https://github.com/BeryJu/oidc-test-client/releases/download/v#{version}/oidc-test-client_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5ae01db66c326dffb71bced49c6ec434f5c9bd5cdd1a8f1897c4d4f465effb96"
      url "https://github.com/BeryJu/oidc-test-client/releases/download/v#{version}/oidc-test-client_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e4a5be8e39870d893a68438d301c19da10bef3d498fbe73686c0b0c3135cfb7f"
      url "https://github.com/BeryJu/oidc-test-client/releases/download/v#{version}/oidc-test-client_#{version}_linux_amd64.tar.gz"
    end
  end

  name "oidc-test-client"
  desc "Small, OIDC Client, to debug and test OIDC providers"
  homepage "https://github.com/beryju/oidc-test-client"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oidc-test-client"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/oidc-test-client"]
    end
  end

  # No zap stanza required
end
