# This file was generated by GoReleaser. DO NOT EDIT.
cask "saml-test-idp" do
  name "saml-test-idp"
  desc "Small, SAML Identity provider for testing and debugging"
  homepage "https://github.com/beryju/saml-test-idp"
  version "0.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "saml-test-idp"

  on_macos do
    on_intel do
      url "https://github.com/BeryJu/saml-test-idp/releases/download/v#{version}/saml-test-idp_#{version}_darwin_amd64.tar.gz"
      sha256 "c4e91aa1d1a37b250081287da3fb8035799a08c18b419afe05464d8b7047e639"
    end
    on_arm do
      url "https://github.com/BeryJu/saml-test-idp/releases/download/v#{version}/saml-test-idp_#{version}_darwin_arm64.tar.gz"
      sha256 "4a79a15b4f836af452655b3509e499c467b85abf8492cd7e805a2baad950ca42"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/BeryJu/saml-test-idp/releases/download/v#{version}/saml-test-idp_#{version}_linux_amd64.tar.gz"
      sha256 "5efdad953cb6ec399b38560d2a4bc6605a1a3a3e3f89d20e90110b4bbdc61bea"
    end
    on_arm do
      url "https://github.com/BeryJu/saml-test-idp/releases/download/v#{version}/saml-test-idp_#{version}_linux_arm64.tar.gz"
      sha256 "8cb3079e1725c9b432c48f3e5ad797ba1d4cf5d392b7aae049bfda92acec620b"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/saml-test-idp"]
    end
  end

  # No zap stanza required
end
