# This file was generated by GoReleaser. DO NOT EDIT.
cask "saml-test-idp" do
  version "0.11"

  on_macos do
    on_arm do
      sha256 "95f3b1ab9ce9aff7d622ffb5daef65fc838f95f66c89dd3f1d094ead7dbe40eb"
      url "https://github.com/BeryJu/saml-test-idp/releases/download/v#{version}/saml-test-idp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b2838a42b987f74aa316e9389954bc4cf7f6908df0b351cc59ab459a21c771b9"
      url "https://github.com/BeryJu/saml-test-idp/releases/download/v#{version}/saml-test-idp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e00612ec773230dde4d8a2efee3b471d08260ca73ed4d2092a593da6c46fcc1e"
      url "https://github.com/BeryJu/saml-test-idp/releases/download/v#{version}/saml-test-idp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "496c2e26cbe7b06e92ee251077f859f73b74e468fe7a62c654309f978c28ca47"
      url "https://github.com/BeryJu/saml-test-idp/releases/download/v#{version}/saml-test-idp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "saml-test-idp"
  desc "Small, SAML Identity provider for testing and debugging"
  homepage "https://github.com/beryju/saml-test-idp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "saml-test-idp"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/saml-test-idp"]
    end
  end

  # No zap stanza required
end
