# This file was generated by GoReleaser. DO NOT EDIT.
cask "saml-test-sp" do
  desc "Small, SAML ServiceProvider for testing and debugging"
  homepage "https://github.com/beryju/saml-test-sp"
  version "1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "saml-test-sp"

  on_macos do
    on_intel do
      url "https://github.com/BeryJu/saml-test-sp/releases/download/v1.4/saml-test-sp_1.4_darwin_amd64.tar.gz"
      sha256 "af9fb85d5e9fd0d00dcbf52a55bbbb231747506a19c2a3eba975e1b8ec1bf777"
    end
    on_arm do
      url "https://github.com/BeryJu/saml-test-sp/releases/download/v1.4/saml-test-sp_1.4_darwin_arm64.tar.gz"
      sha256 "0fa1b071d872153b34e63cefe80833ba645db5d7dfe430c5f693b5218f1840da"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/BeryJu/saml-test-sp/releases/download/v1.4/saml-test-sp_1.4_linux_amd64.tar.gz"
      sha256 "ee1d61a28a2ef84eef9de301f82c51497ed1b47611d38f9b3215539f07e8ab06"
    end
    on_arm do
      url "https://github.com/BeryJu/saml-test-sp/releases/download/v1.4/saml-test-sp_1.4_linux_arm64.tar.gz"
      sha256 "26c3a9e9bdf2d971edd81b0ce96f1d265e4f522045e884007aecdb67b9e70a9e"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/saml-test-sp"]
    end
  end

  # No zap stanza required
end
