# This file was generated by GoReleaser. DO NOT EDIT.
cask "saml-test-idp" do
  version "0.10"

  on_macos do
    on_arm do
      sha256 "ef8994c5aee78cf4b53acdfebc032ed0ec1165d446e44b83d902a61191c08c3c"
      url "https://github.com/BeryJu/saml-test-idp/releases/download/v#{version}/saml-test-idp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "88588c93310723c08464f48cc2082e0061cd842c7e3a6edf34fd2c8767c1774b"
      url "https://github.com/BeryJu/saml-test-idp/releases/download/v#{version}/saml-test-idp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "241bb0719f034afe107145048a27b917a6d8269928175d60a798fcf450edf599"
      url "https://github.com/BeryJu/saml-test-idp/releases/download/v#{version}/saml-test-idp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8ce2fe5123c3ca84060c285b6ed83f5a439ba32163ceb64c0f3108776ea50a22"
      url "https://github.com/BeryJu/saml-test-idp/releases/download/v#{version}/saml-test-idp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "saml-test-idp"
  desc "Small, SAML Identity provider for testing and debugging"
  homepage "https://github.com/beryju/saml-test-idp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "saml-test-idp"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/saml-test-idp"]
    end
  end

  # No zap stanza required
end
