# This file was generated by GoReleaser. DO NOT EDIT.
cask "saml-test-sp" do
  desc "Small, SAML ServiceProvider for testing and debugging"
  homepage "https://github.com/beryju/saml-test-sp"
  version "1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "saml-test-sp"

  on_macos do
    on_intel do
      url "https://github.com/BeryJu/saml-test-sp/releases/download/v1.3/saml-test-sp_darwin_amd64"
      sha256 "d9405310af4906822c348ba6721d7a1372fb5277e1ced25b6214fff90acb0fea"
    end
    on_arm do
      url "https://github.com/BeryJu/saml-test-sp/releases/download/v1.3/saml-test-sp_darwin_arm64"
      sha256 "61349605caea11781e81fa7aad9c91b25153cc7d847f07a70996921e4e20cb50"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/BeryJu/saml-test-sp/releases/download/v1.3/saml-test-sp_linux_amd64"
      sha256 "6e4e63217f59f35c8da67d8cfce3abf4b62c303261fef7545f7948562a609a1c"
    end
    on_arm do
      url "https://github.com/BeryJu/saml-test-sp/releases/download/v1.3/saml-test-sp_linux_arm64"
      sha256 "021a45160406bfa387d747fe423aef998c241a06a199bc4366da2bfa6af897f7"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/saml-test-sp"]
    end
  end

  # No zap stanza required
end
