# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Korb < Formula
  desc "Move Kubernetes PVCs between Storage Classes and Namespaces"
  homepage "https://github.com/beryju/korb"
  version "2.3.2"

  on_macos do
    on_intel do
      url "https://github.com/BeryJu/korb/releases/download/v2.3.2/korb_darwin_amd64"
      sha256 "027e732bfbebaa4c538d7be891f1429f89ab7a3b2130dd57eea2bf50e1990cef"

      def install
        bin.install "korb_darwin_amd64" => "korb"
      end
    end
    on_arm do
      url "https://github.com/BeryJu/korb/releases/download/v2.3.2/korb_darwin_arm64"
      sha256 "e2c3445882ce94fbcf3cd2a98147792d68dc5c73d13385c908460a3cfb3279a5"

      def install
        bin.install "korb_darwin_arm64" => "korb"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/BeryJu/korb/releases/download/v2.3.2/korb_linux_amd64"
        sha256 "1216c48d2fb9db9641e485a4554cd2127ef72f35be3cbe502ad8cc8110328e15"

        def install
          bin.install "korb_linux_amd64" => "korb"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/BeryJu/korb/releases/download/v2.3.2/korb_linux_arm"
        sha256 "35d7ee20a0ae33767ae8f58e244442bd36ff7404a09d82aa63aaa7e9ecd1c826"

        def install
          bin.install "korb_linux_arm" => "korb"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/BeryJu/korb/releases/download/v2.3.2/korb_linux_arm64"
        sha256 "cfea119f100b463d098a5d5eff21d8672c264714b56d545be8106cc345e96bad"

        def install
          bin.install "korb_linux_arm64" => "korb"
        end
      end
    end
  end
end
