# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OidcTestClient < Formula
  desc "Small, OIDC Client, to debug and test OIDC providers"
  homepage "https://github.com/beryju/oidc-test-client"
  version "2.4"

  on_macos do
    on_intel do
      url "https://github.com/BeryJu/oidc-test-client/releases/download/v2.4/oidc-test-client_darwin_amd64"
      sha256 "5c845ceb6d6b8974c785a55d47f0d07f476357937446e8ec12d92b67e673a8c0"

      def install
        bin.install "oidc-test-client_darwin_amd64" => "oidc-test-client"
      end
    end
    on_arm do
      url "https://github.com/BeryJu/oidc-test-client/releases/download/v2.4/oidc-test-client_darwin_arm64"
      sha256 "81a0aa7b950db06e7c67654237c71d75b462957ef8b8a7970a3bde911e0bf970"

      def install
        bin.install "oidc-test-client_darwin_arm64" => "oidc-test-client"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/BeryJu/oidc-test-client/releases/download/v2.4/oidc-test-client_linux_amd64"
        sha256 "e73d8acfb05baed890b056aee0a6903b95a5b5355c73dd7140cb17250167296a"

        def install
          bin.install "oidc-test-client_linux_amd64" => "oidc-test-client"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/BeryJu/oidc-test-client/releases/download/v2.4/oidc-test-client_linux_armv6"
        sha256 "f5619a48170ee0321f18b25892acfbf614687ebf8511cc807a55d76bde58bd86"

        def install
          bin.install "oidc-test-client_linux_armv6" => "oidc-test-client"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/BeryJu/oidc-test-client/releases/download/v2.4/oidc-test-client_linux_arm64"
        sha256 "b78102ae86e15a7e1ead306b49ec34cb9d866742a5620a5a1c8c51fb32cf5f19"

        def install
          bin.install "oidc-test-client_linux_arm64" => "oidc-test-client"
        end
      end
    end
  end
end
